version: 2.1

parameters:
  ApiTrigger:
    type: boolean
    default: false

  SmokeTrigger:
    type: boolean
    default: false

  browser:
    type: string
    default: chrome

jobs:
  build:
    parameters:
      e2eCommand:
        type: string
        default: npm run test -- --browser << pipeline.parameters.browser >>
    docker:
      - image: cypress/browsers:latest
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run e2e
          command: << parameters.e2eCommand >>
          no_output_timeout: 180m

      - run:
          name: Generate mocha report
          command: npm run mochawesome:merge
          when: always

      - store_artifacts:
          name: Report uploading
          path: mochawesome-report/
          destination: reports/
      - store_artifacts:
          name: Videos uploading
          path: cypress/videos/
          destination: videos/
      - store_artifacts:
          name: Screenshots uploading
          path: cypress/screenshots/
          destination: screenshots/

workflows:
  version: 2
  commit:
    unless: << pipeline.parameters.ApiTrigger >>
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

  smoke:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          e2eCommand: CYPRESS_INCLUDE_TAGS=smoke npm run test -- --browser << pipeline.parameters.browser >>

  smoke_on_demad:
    when: << pipeline.parameters.SmokeTrigger>>
    jobs:
      - build:
          e2eCommand: CYPRESS_INCLUDE_TAGS=smoke npm run test -- --browser << pipeline.parameters.browser >>
          filters:
            branches:
              only:
                - master

  on_demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
